version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/deepstock
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: deepstock/scripts/after-deploy.sh
      timeout: 180