name: deploy

on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.SPEM  }}
          HOSTNAME: ${{ secrets.IP  }}
          USER_NAME: ${{ secrets.USERNAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
          
            cd /home/ubuntu/deepstock &&
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master