name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master

      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: ls
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY}}