name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master

      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          debug: true
          timeout: 30s
          command_timeout: 30s
          script: | 
            cd deepstock
            ls -a
            git pull
            sh kill.sh
            nohup pipenv run python3 main.py > nohup.out 2> nohup.err < /dev/null &
            
            echo "start"
            exit