name: deploy

on:
  push:
    branches:
      - main

jobs:
  SSH:
    steps:
      runs-on: ubuntu-latest
      steps:
        - name: Install SSH key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_KEY }}
            known_hosts: ${{ secrets.KNOWN_HOST }}
